public class ogrenci12 {
    public ogrenci12(){
        system.debug('Yeni bir ogrenci kayit oldu. Hayirli olsun..');
    }

     

   public string firstName;
   public string lastName;
   private string schoolName = 'Dream School';
   public string classname;
   public boolean art;
   public boolean sport;
   public integer ingGrade;
   public integer mathGrade;
   public integer sciGrade;




}
