public class SalesforceDeveloper {
    public void myFirstCode(){
        string favoriteCity = 'NYC';
        string favoriteMovie = 'Breaking Bad';
        string favoriteSeason = 'Spring';

        system.debug(favoriteCity);
        system.debug(favoriteMovie);
        system.debug(favoriteSeason);
    }

    public void myFavorites(){
        string myCity = 'Mersin';
        system.debug(myCity);

        integer myNumber = 33;
        system.debug(myNumber);

        system.debug(' Favori numaram -> ' + myNumber + ' ve favori sehrim ' + myCity);

    }
}
