IfandForLop12 if1 = new IfandForLop12();
if1.ifNumbers(5, 11);
if1.ifNumbers(23,14);
if1.ifNumbers(15,15);

IfandForLop12 if2 = new IfandForLop12();
if2.ifBread('simit', 3);
if2.ifBread('kek', 2);
if2.ifBread('ekmek', 1);
if2.ifBread('ayran', 4);

IfandForLop12 if3 = new IfandForLop12();
if3.ifBreadSwitch('simit', 4);
if3.ifBreadSwitch('kek', 2);
if3.ifBreadSwitch('ekmek',3);
if3.ifBreadSwitch('cay', 1);

IfandForLop12 if4 = new IfandForLop12();
if4.forLoopSumNumbers(3);